# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRbaXabGuwEWeSqvhH4fRUCqYFFGJuYB
"""

#SUM OF DIGITS OF 4 DIGIT NUMBER
#REVERSE OF THE NUMBER
#DIFFERENCE BETWEEN PRODUCT OF DIGITS AT EVEN POSITION AND PRODUCT OF DIGITS AT EVEN POSITION

num=int(input("Enter any four digit number"))
p=num
a=num%10
num=num/10
b=num%10
num=num/10
c=num%10
num=num/10
d=num%10
num=num/10

e=a*c
f=b*d
print("sum of digits: ",a+b+c+d)
print("Difference between product of digits at odd position and product of digits at even position", e-f)