# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hg4w_IGHYaw_5hoKCDF1s9lE2HSB1P5J
"""

import math

def sidesoftri():
  a1=int(input("Enter side1 of triangle1"))
  b1=int(input("Enter side2 of triangle1"))
  c1=int(input("Enter side3 of triangle1"))
  a2=int(input("Enter side1 of triangle2"))
  b2=int(input("Enter side2 of triangle2"))
  c2=int(input("Enter side3 of triangle2"))
  return a1,b1,c1,a2,b2,c2

def area(a,b,c):
    s=(a+b+c)/2
    A=(s*(s-a)*(s-b)*(s-c))**0.5
    return A

a1,b1,c1,a2,b2,c2=sidesoftri()
area1=area(a1,b1,c1)
area2=area(a2,b2,c2)
print("\nArea1 = ",area1)
print("\nArea2 = ",area2)  

Total_area=area1+area2
print(Total_area)

Contribution_of_tri1=(area1/(area1+area2))*100
print("Contribution of triangle1= ", Contribution_of_tri1)
Contribution_of_tri2=(area2/(area1+area2))*100
print("Contribution of triangle2= ", Contribution_of_tri2)