# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cmyKqcqRhu3WT7x8mbxSkmT0xYGvB7yx
"""

#Define a function to check if a number is happy or not
#Define a fuunction to print all happy numbers in a range
#Define a function to print first N happy numbers

num = int(input("Enter a number "))
def happy(num):
    n = num
    for i in range(100):
        p = 0
        while n!= 0:
            r = n%10
            p += r*r
            n = n//10
        n = p
        if p == 1:
           return True
    return False
if happy(num) == True:
    print("Happy")
else:
    print("Sad")
def range():
    r1=int(input("\nEnter starting range: "))
    r2=int(input("Enter ending range: "))
    print("\nHappy numbers from ",r1," to ",r2," are: ")
    for i in range(r1,r2+1):
        if happy(i)==True:
           print(i)
range()

def n_happy():
    n = int(input("\nNo. of happy numbers: "))
    print("First ",n," happy numbers: ")
    i=0
    while n != 0:
        i += 1
        if happy(i) == True:
            n -= 1
            print(i)
n_happy()